#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME				=	Package identify which is defined in INFO
# SYNOPKG_PKGVER				=	Package version which is defined in INFO
# SYNOPKG_PKGDEST				=	Package destination path
#                       			/volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER 	= 	Temporary upgrade folder
#                                   /volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------


# Important Paths, soft links and variables
# -------------------------------------------------------------------------------------
# DSM WebGUI folder
# /usr/syno/synoman/webman/3rdparty/[Package Name] -> /var/packages/[Package Name]/target
WEBGUI_FOLDER="/usr/syno/synoman/webman/3rdparty/${SYNOPKG_PKGNAME}"

# Soft link
# /var/packages/[Package Name]/target -> /volume1/@appstore/[Package Name]
PACKAGE_FOLDER="/var/packages/${SYNOPKG_PKGNAME}/target/ui"

# Timestamp - Formatting the Timestamp to terminate log entries
TIMESTAMP=`date +%Y-%m-%d%t%H:%M:%S`
# -------------------------------------------------------------------------------------


# Action...
# -------------------------------------------------------------------------------------

if [ ! -d "${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings" ]; then
	mkdir -p -m 755 ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
fi

echo ''${TIMESTAMP}' - Start package update --> '${SYNOPKG_PKGNAME}' '${SYNOPKG_PKGVER}'' >>/tmp/${SYNOPKG_PKGNAME}.history

if [ -d "${WEBGUI_FOLDER}/usersettings" ]; then
    cp -rf ${WEBGUI_FOLDER}/usersettings/* ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
	echo ''${TIMESTAMP}' - Backup user settings from '${WEBGUI_FOLDER}'/usersettings to '${SYNOPKG_TEMP_UPGRADE_FOLDER}'/usersettings' >>/tmp/${SYNOPKG_PKGNAME}.history
else
		echo ''${TIMESTAMP}' - Backup user settings failed' >>/tmp/${SYNOPKG_PKGNAME}.history
fi

exit 0