#!/bin/sh

case $1 in
	start)
		### Start this package.
		LogAnalysis "Start"
		# echo "The package has been started" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	stop)
		### Stop this package.
		LogAnalysis "Stop"
		# echo "The package has been stopped" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	status)
		### Check package alive.
		if [ -h "/usr/local/bin/LogAnalysis" ]; then
			exit 0
		else
			exit 1
		fi
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac
